Create Core Models
SprocketBot/database-service pull request #1
Opened 2021-06-29 03:55 UTC by 0c370t

2021-06-30 03:30 UTC, zachstence requested changes

2021-06-30 03:30 UTC, zachstence commented on src/franchise/roster_role.model.ts
> +    code: string;
Should `code` columns on all tables be enums? They should be dynamic-ish, but also some sort of type safety over magic strings would be nice, something to revisit

2021-06-30 03:30 UTC, zachstence commented on src/franchise/roster_role.model.ts
> +    game: Game;
Should we have a relationship to a `GameSkillGroup` as well? E.g., Foundation League has smaller rosters than the other leagues (I think? Or maybe I'm dumb)

2021-06-30 03:30 UTC, zachstence commented on src/franchise/roster_role_usages.model.ts
> +    match: Match;
Probably need some sort of uniqueness constraint here

2021-06-30 03:30 UTC, zachstence commented on src/franchise/roster_role_use_limits.model.ts
> +    @JoinColumn()
I think the `GameSkillGroup` should own this relationship. A game skill group has some specified roster role use limits, not the other way around.

2021-06-30 03:30 UTC, zachstence commented on src/franchise/roster_slot.model.ts
> +export class RosterSlot extends BaseModel {
Uniqueness?

2021-06-30 03:30 UTC, zachstence commented on src/franchise/team.model.ts
> +export class Team extends BaseModel {
Uniqueness?

2021-06-30 03:30 UTC, zachstence commented on src/game/game.module.ts
> +            Feature,
Is this missing `EnabledFeature`, `GamePlatform`, `GameFeature`, and `FeatureDependency`?

2021-06-30 03:30 UTC, zachstence commented on src/organization/approval.model.ts
> +export class Approval extends BaseModel {
Missing a column for the `Member` that issued the `Approval`

2021-06-30 03:30 UTC, zachstence commented on src/organization/organization.module.ts
> +            Pronouns,
Is this missing `Approval` and `Photo`?

2021-06-30 03:30 UTC, zachstence commented on src/organization/photo.model.ts
> +    url: string;
Why would this be nullable? There's no photo without an associated URL

If it is nullable, it should be `url?`

2021-06-30 03:30 UTC, zachstence commented on src/organization/pronouns.model.ts
> +    possessiveAdjective: string;
`posessiveAdjectivePronoun` for consistency

2021-06-30 03:30 UTC, zachstence commented on src/scheduling/eligibility_data.model.ts
> +export class EligibilityData extends BaseModel {
Missing `Player` relationship

2021-06-30 03:30 UTC, zachstence commented on src/scheduling/match.model.ts
> +    @OneToOne(() => Invalidation)
Need a `@JoinTable` here, the `Match` has an `Invalidation`

2021-06-30 03:30 UTC, zachstence commented on src/scheduling/match_parent.model.ts
> +export class MatchParent extends BaseModel {
Missing relationships to `Scrim` and `ScheduleFixture`

2021-06-30 03:30 UTC, zachstence commented on src/scheduling/schedule_group.model.ts
> +    description: string;
Should be `description?` since its `nullable`

2021-06-30 03:30 UTC, zachstence commented on src/scheduling/schedule_group_type.model.ts
> +
Should this have a `code` field similar to other tables?

2021-06-30 03:30 UTC, zachstence commented on src/scheduling/team_stat_line.model.ts
> +    teamName: string;
Should this be a `Team`?

2021-06-30 03:30 UTC, zachstence commented on src/authorization/organization_staff_seat.model.ts
> +    member: Member;
Should be `member?` since its `nullable`

2021-06-30 03:30 UTC, zachstence commented on src/scheduling/match_parent.model.ts
> +    event: ScheduledEvent;
Should be `event?` since its `nullable`

2021-06-30 03:30 UTC, zachstence commented on src/scheduling/round.model.ts
> +    invalidation: Invalidation;
Should be `invalidation?` since its `nullable`

2021-06-30 03:30 UTC, zachstence commented on src/scheduling/scheduled_event.model.ts
> +    matchParents: MatchParent;
Should have null qualifiers `?` since they're `nullable`

2021-06-30 03:30 UTC, 0c370t commented on migrations/1624938775147-Automigration.ts
> +import {MigrationInterface, QueryRunner} from "typeorm";
Yes

2021-06-30 03:30 UTC, 0c370t commented on config/default.json
> +    "password": "",
Probably not

2021-06-30 03:31 UTC, 0c370t commented on src/app.module.ts
> +        }),
They need to be different, ormconfig.js is only used for generating migrations

2021-06-30 03:31 UTC, 0c370t commented on src/app.module.ts
> +        AuthorizationModule],
Line 32

2021-06-30 03:31 UTC, 0c370t commented on src/base-model.ts
> +    deletedAt: Date;
We can add later

2021-06-30 03:37 UTC, 0c370t commented on src/authorization/franchise_leadership_role.model.ts
> +    @OneToOne(() => PermissionBearer)
`@JoinColumn`?

2021-06-30 03:38 UTC, 0c370t commented on .eslintrc.js
>          "@typescript-eslint",
Lets create a ticket for that

2021-06-30 03:38 UTC, 0c370t commented on src/configuration/organization_configuration_value.model.ts
> +    allowedValue?: OrganizationConfigurationAllowedValue;
That's a runtime concern, can't do anything with that at this level

2021-06-30 23:19 UTC, 0c370t commented on src/app.module.ts
> +        }),
Different i.e. cannot be reused

2021-06-30 23:21 UTC, 0c370t commented on src/authorization/franchise_leadership_role.model.ts
> +import {
File names are done per NestJS' conventions, many of these files were generated with the CLI (and I then went and wrote the models inside)

2021-06-30 23:30 UTC, 0c370t commented on src/franchise/franchise_profile.model.ts
> +    code: string;
`PAN` `SHA`, might want to rename it to something else

2021-06-30 23:31 UTC, 0c370t commented on src/franchise/game_skill_group.model.ts
> +    salaryCap: number;
I quite like `-1`, it's more deliberate than `null`

2021-06-30 23:32 UTC, 0c370t commented on src/franchise/game_skill_group.model.ts
> +    roleUseLimits: RosterRoleUseLimits;
Schema we came up with has the role use limits owning it, it's an easy change before we deploy anything, can discuss

2021-06-30 23:32 UTC, 0c370t commented on src/franchise/roster_role.model.ts
> +    code: string;
If they are fully dynamic, we won't be able to enumerate them (nor should we, imo)

2021-06-30 23:33 UTC, 0c370t commented on src/franchise/roster_role.model.ts
> +    game: Game;
This is probably a larger question, if we link to game skill group you would need to make PlayerA 5 times for the current MLE configuration

2021-06-30 23:33 UTC, 0c370t commented on src/franchise/roster_role_use_limits.model.ts
> +    @JoinColumn()
Moved

2021-06-30 23:34 UTC, 0c370t commented on src/franchise/roster_slot.model.ts
> +export class RosterSlot extends BaseModel {
We should discuss these

2021-06-30 23:36 UTC, 0c370t commented on src/game/game.module.ts
> +            Feature,
GamePlatform and FeatureDependency are join tables, not explicit models now, however EnabledFeature was missing

2021-06-30 23:39 UTC, 0c370t commented on src/organization/photo.model.ts
> +    url: string;
Would be nullable if we create the photo and then let a user upload a picture, doesn't need to stick this way

2021-06-30 23:39 UTC, 0c370t commented on src/organization/pronouns.model.ts
> +    possessiveAdjective: string;
But this is not a pronoun, this is a [possessive adjective](https://www.grammar-monster.com/glossary/possessive_adjectives.htm)

2021-06-30 23:42 UTC, 0c370t commented on src/scheduling/team_stat_line.model.ts
> +    teamName: string;
No, but we probably should have `Team` here, not all team stat lines will involve a `Team`, i.e. scrims

2021-07-01 23:58 UTC, zachstence commented on .eslintrc.js
>          "@typescript-eslint",
Created issue #2

2021-07-01 23:58 UTC, zachstence commented on src/base-model.ts
> +    deletedAt: Date;
Created issue #3

2021-07-01 23:58 UTC, zachstence commented on src/authorization/franchise_leadership_role.model.ts
> +    @OneToOne(() => PermissionBearer)
Yes

2021-07-02 00:01 UTC, zachstence commented on src/franchise/franchise_profile.model.ts
> +    code: string;
Okay. Will be explained in a JSDoc comment

2021-07-02 00:16 UTC, zachstence commented on src/franchise/roster_role.model.ts
> +    game: Game;
Will be fixed

2021-07-02 00:21 UTC, zachstence approved these changes

2021-07-02 00:21 UTC, zachstence commented on src/franchise/roster_slot.model.ts
> +export class RosterSlot extends BaseModel {
Issue created #4

2021-07-02 00:21 UTC, zachstence commented on src/franchise/team.model.ts
> +export class Team extends BaseModel {
Issue created #4

2021-07-02 00:21 UTC, zachstence commented on src/organization/pronouns.model.ts
> +    possessiveAdjective: string;
fair

2021-07-02 00:25 UTC, zachstence commented on src/scheduling/match_parent.model.ts
> +export class MatchParent extends BaseModel {
Sov is fixing

2021-07-02 00:26 UTC, merged